### ISSUE TITLE
Typo in "uploaded"

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#1]
There is a type in "Successfully uplaoded!"

It should be "Successfully uploaded!"

**Comment by ProfessorFarnsworth** [comment]
I've seen that and already fixed it! The next version should contain the fix. But thank you for letting me know!

**Comment by bjarnef** [comment]
Cool! You can just close the issue then :)

**Comment by ProfessorFarnsworth** [comment]
Yeah I'll close it when the new Package is uploaded. To track it correctly. :) Otherwise I'll forget to check it before I upload the new package.

**Comment by bjarnef** [comment]
Okay I just closed it :) .. I'll keep an eye on that ;)

**Comment by ProfessorFarnsworth** [comment]
Thanks!
