### ISSUE TITLE
Only remove files when clicking link and filesizes in KB, MB, GB

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#10]
Can you make sure files only are removed when you click the links? Right right they can be removed by clicking the background e.g. in the right part of the droparea.

Furthermore instead og displaying the size in bytes, e.g. 1920297 Bytes I think it might be more friendly to editors to understand KB, MB, GB?

You could follow this way, when to convert to KB, MB, GB https://our.umbraco.org/wiki/reference/code-snippets/listfilesfrommediafolderxslt/find-media-file-sizes

**Comment by ProfessorFarnsworth** [comment]
Of course :)

**Comment by ProfessorFarnsworth** [comment]
Fixed and implemented :)
