### ISSUE TITLE
Folder not listing files (only images) like in core

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#11]
Folder is not listing files (only images) like the core property editor does. For files maybe just use a font-icon + filename (see the core property editor).

![2015-02-05_19-46-59](https://cloud.githubusercontent.com/assets/2919859/6066813/431c510a-ad70-11e4-95dc-04e33fc9992b.jpg)

**Comment by ProfessorFarnsworth** [comment]
It's already on my to do list and also already implemented. I just need to create a package for it ;)

**Comment by bjarnef** [comment]
Haha great :) .. I was late then :-P 
But better to report an issue too much than not at all ;)

**Comment by ProfessorFarnsworth** [comment]
No problem :) I'm fine with all the feedback I get!

**Comment by ProfessorFarnsworth** [comment]
Implemented :) Enjoy!
