### ISSUE TITLE
If Umbraco session expires while uploading display error message

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#12]
I exspirienced that Umbraco sessions expired while some files were uploading and after I logged back in, the console displayed 401 (Unauthorized) and red status bar in the upload.

If that happens could we display an error message? Maybe display a default error message for when alert-error is displayed? and then change the text if there is a more specific reason?

There were two files that wasn't successfully uploaded and not created as nodes, probably while it was processing the images.

![2015-02-06_00-02-18](https://cloud.githubusercontent.com/assets/2919859/6071268/387a0462-ad94-11e4-9338-af5c6d47733f.jpg)

**Comment by ProfessorFarnsworth** [comment]
Yes of course! I'm wondering why the message isn't displayed. Kind of weird thing!

**Comment by ProfessorFarnsworth** [comment]
This issue should be handled now. Well I created a generic error for it.
