### ISSUE TITLE
Hold empty placeholder for remove button

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#13]
Great that there is added a remove button, so you can remove the "lines" after successfully upload. However there should be an empty placeholder for remove button, so the lines fit into the "grid" vertically too :)

Maybe place the percent close to the progressbar too?

![2015-02-06_12-54-13](https://cloud.githubusercontent.com/assets/2919859/6079001/f3a8caaa-adff-11e4-9510-03e2f06cdcd3.jpg)

**Comment by ProfessorFarnsworth** [comment]
Yes that's right! I gonna correct that.

**Comment by ProfessorFarnsworth** [comment]
I've change the style of the whole upload progress a bit. So this should be corrected :)
