### ISSUE TITLE
Black border/background on images

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#14]
I noticed there is a black border or background on images. Is it using ImageProcessor to scale the images? I think I have seem it before.

I think it is because of wrong calculated image size. The original image size of the one hightlighted is 5412 x 6843 ( w x h).. using http://andrew.hedges.name/experiments/aspect_ratio/ and set W2 to 94px (as the scaled image) it tells me the H2 (resized height) should be 119px, but in this view it is 120px, which probably is the reason of the black border at the bottom.
The the view in core of Umbraco the image is scaled correct according to aspect ratio.

![2015-02-06_15-15-05](https://cloud.githubusercontent.com/assets/2919859/6080645/6de64adc-ae13-11e4-96ab-bc098e565659.jpg)

![2015-02-06_15-15-16](https://cloud.githubusercontent.com/assets/2919859/6080648/7298dc34-ae13-11e4-9a27-35c267052bd8.jpg)

![2015-02-06_15-26-45](https://cloud.githubusercontent.com/assets/2919859/6080807/b68ac82a-ae14-11e4-85e8-b0a9fa4aa293.jpg)

**Comment by ProfessorFarnsworth** [comment]
Hey, 

have you enabled the resizing feature or are the images uploaded as is?

I'm using the GDI+ to resize the images if the feature is enabled. Otherwise it might be a ImageProcessor bug or something.

**Comment by bjarnef** [comment]
Just a Umbraco 7.2.0 with default settings. Images are uploaded it original size, e.g. 5412 x 6843 px.

**Comment by bjarnef** [comment]
Tried locally with a 7.2.1 install and got som strange issues. It didn't upload files that was < 4 MB.
The black border I think is because of Image Processor, when the aspect ratio doesn't fit. I have seen than in frontend if I force an image in bad proportions.

But still it doesn't seem to happen for the core view where it list the images.

![2015-02-06_16-16-00](https://cloud.githubusercontent.com/assets/2919859/6081678/cf971740-ae1b-11e4-836f-214d112a3bc9.jpg)

![2015-02-06_16-16-46](https://cloud.githubusercontent.com/assets/2919859/6081682/d430e2cc-ae1b-11e4-9dc7-693fb3673225.jpg)

**Comment by bjarnef** [comment]
Hmm, that is strange. Style_13.jpg is a jpg image and was generated as a media file.

![2015-02-06_16-22-41](https://cloud.githubusercontent.com/assets/2919859/6081798/a4117308-ae1c-11e4-80bf-e89f42dcdae1.jpg)

**Comment by bjarnef** [comment]
It seems to work okay if I choose a single image, but if I choose a bunch of images (10 images), it has some issues. All these images are smaller than 4 MB.

![2015-02-06_16-26-52](https://cloud.githubusercontent.com/assets/2919859/6081926/62eb25c6-ae1d-11e4-94a4-ee13ad268495.jpg)
![2015-02-06_16-27-14](https://cloud.githubusercontent.com/assets/2919859/6081927/62ed4018-ae1d-11e4-8ea5-cbe1577aaf44.jpg)

**Comment by ProfessorFarnsworth** [comment]
The errors look like the umbraco (iis) process is running out of memory :D

**Comment by bjarnef** [comment]
Not sure if it make a difference that with 7.2.0 I tested online on a demo site, and with 7.2.1 locally running through WebMatrix.

**Comment by bjarnef** [comment]
Look like some internal errors happens:

![2015-02-06_16-37-56](https://cloud.githubusercontent.com/assets/2919859/6082090/be67ebea-ae1e-11e4-93e2-5447e4e3de8b.jpg)
![2015-02-06_16-38-22](https://cloud.githubusercontent.com/assets/2919859/6082089/be654354-ae1e-11e4-8257-b6aeecb09468.jpg)

**Comment by ProfessorFarnsworth** [comment]
Yeah those are the GDI+ and Out of memory. I'm displaying the exception messages.
Could you have a look at your memory for the WebMatrix process?
Over here the upload of larger files are causing a small memory peek. Maybe that's to much for the webmatrix iis express.

**Comment by bjarnef** [comment]
Before uploading:

![2015-02-06_16-46-22](https://cloud.githubusercontent.com/assets/2919859/6082238/1bbda23e-ae20-11e4-8793-f123dc16cead.jpg)

Then it goes crazy :-P
![2015-02-06_16-48-13](https://cloud.githubusercontent.com/assets/2919859/6082242/237c0006-ae20-11e4-9ec3-0a4098ba070b.jpg)

**Comment by ProfessorFarnsworth** [comment]
Well I supose

**Comment by ProfessorFarnsworth** [comment]
Well I suppose that Hukom... means RAM :D and it doesn't seem to peak that much. The disk thing, as far as I know, is bug in Win8 and doesn't reflect the Disk usage.
But I think I can do something about that issue. But it will take a bit. Maybe don't use this plugin within a WebMatrix installation atm.
Thanks for you analyze though.

**Comment by ProfessorFarnsworth** [comment]
There is now a newer version available (0.2.0). I've improved the image handling to avoid high memory usage. Hopefully it fixes your problem.

Regarding the black border. As I'm using GetCropUrl(...) I think it is a ImageProcessor bug. Maybe I implement a workaround one day but for now it's ok :)

The other issue with an image uploaded as file is a bit weird but I think that the .Net Image Class doesn't understand that image correctly. Maybe you can send me that file for some tests.

**Comment by bjarnef** [comment]
I upgraded the package, but unfortunately it is still an issue - not just with a single image, but when you upload a bunch of images.

Try upload these four images at the same time:
http://www.lightair.dk/media/21485/lightair-evolution-led_july2014.jpg
http://www.lightair.dk/media/21488/lightair-signature-led_july2014.jpg
http://www.lightair.dk/media/21490/lightair-style-led_july2014.jpg
http://www.lightair.dk/media/21476/Lightair_Solution-1-.jpg

I have tried a couple of times and only Lightair_Solution-1-.jpg is successfully uploaded, the other ones fails with "Out of memory". If I upload 10 images I also see the "A generic error occurred in GDI+" error a couple of times.

Could you maybe upload this image http://dev.bjarnefyrstenborg.dk/Surface_6.jpg (5412 x 6843 px) ... maybe take a look at this forum post: https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/57741-GetCropUrl-with-ImageCropModePad-results-in-black-bars-on-the-sides

The full documentation of ImageProcessor is here: http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#methods

The image that was created as a file, was create correctly as an image, when I uploaded it alone. But an issue when uploading multiple files. When I uploading the following 10 images at same time, some failed and "Surface_8.jpg" and "Style_11.jpg" was created as media files.

http://dev.bjarnefyrstenborg.dk/lightair/Signature_2.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Sky_6.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Style_10.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Style_11.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Style_12.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Style_13.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Surface_5.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Surface_6.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Surface_7.jpg
http://dev.bjarnefyrstenborg.dk/lightair/Surface_8.jpg

**Comment by ProfessorFarnsworth** [comment]
Thanks for the sample files! I'll try them. Maybe you can disable the resize and quality option in the data type settings for now? Because the new version 0.2.0 shouldn't cause that problem.

**Comment by bjarnef** [comment]
I haven't even used these settings :)

**Comment by bjarnef** [comment]
Okay, even this single image fails to upload with "Out of memory"
http://www.lightair.dk/media/21485/lightair-evolution-led_july2014.jpg

**Comment by ProfessorFarnsworth** [comment]
But you use the latest version? 0.2.0? Because this version only copies the as you might see in the source files.

**Comment by bjarnef** [comment]
Yes, I use v. 0.2.0 and Umbraco 7.2.1

**Comment by bjarnef** [comment]
Just saw this file upload: http://www.encodedna.com/reviews/infragistics/jquery-file-upload.htm
Demo: http://www.infragistics.com/samples/aspnet/web-upload/multiple-upload

Maybe you can use some of it as inspiration - not the specific code, more the features or some of the UI.

**Comment by ProfessorFarnsworth** [comment]
Yeah not bad. Maybe I get some inspiration :D
Anyway. Could you check the Umbraco log file for the detailed error message. Because as said I'm really wondering what this issue is caused by :( In the meantime a gonna double check my source.

**Comment by bjarnef** [comment]
Yeah, unfortunately Umbraco log file doesn't show any error messages. I didn't really see any issues when I test online http://umb7.bjarnefyrstenborg.dk/ ... but I got the error message locally when running the Umbraco installation through WebMatrix.

But maybe you could log the exceptions if some errors happens?
http://24days.in/umbraco/2013/log4net-in-umbraco/

**Comment by ProfessorFarnsworth** [comment]
That's what I'm working on right now ;)
I just need to test it in my WebMatrix Environment once and than if you still like to download the .dll.
I'll let you know when I'm done.

**Comment by ProfessorFarnsworth** [comment]
FINALLY :D I found the issue. Thanks to your files (Only happens with them).
The downside though is that I can't do really much about it. Something in the GDI+ (also used by Umbraco) causes this issue.

This line is the troublemaker:
Services.MediaService.Save(media, int.Parse(userId), true);

If I change the boolean at the end to false it works.
Services.MediaService.Save(media, int.Parse(userId), false);

BUT ... If I keep it at false and try to upload mutliple files at once... bam all uploaded images are detected as Files caused by my GDI+ method to detect if it is an image or not tells me that the uploaded file is not a image. (See function IsImage(...))
So sad to say something in the IIS Express is probably messing around with the memory and mixing the bits and bytes. Sounds weird? For me as well but the only explanation I do have atm. Maybe it is a bug in the IIS Express with multiple threads or so.

My solution would be to upload every image one by one. Which would slow down the upload process overall but I could guarantee that all images are uploaded and associated correctly.

So I think I'm going to implement that workaround.

Hopefully my description makes sense to you ;) Otherwise I gonna try to explain a bit more detailed.
Or you just ask what where you would need more information about.

Best Regards,
Helmuth

**Comment by bjarnef** [comment]
well, as my earlier comment I also exspirienced it with just uploading a single file :)

"... even this single image fails to upload with "Out of memory"
http://www.lightair.dk/media/21485/lightair-evolution-led_july2014.jpg"

**Comment by bjarnef** [comment]
Ahh okay, I got this exception in log after uploading the images through Umbraco's core upload:

```
System.OutOfMemoryException: Der er ikke mere hukommelse.
   ved System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   ved ImageProcessor.ImageFactory.Load(String imagePath)
   ved ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__b.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   ved System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   ved System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
2015-02-07 20:15:16,562 [11] INFO  umbraco.BusinessLogic.Log - [Thread 30] Log scrubbed.  Removed all items older than 2014-12-09 20:15:16
```

**Comment by bjarnef** [comment]
Hmm, might still be an issue in Umbraco:
http://issues.umbraco.org/issue/U4-3844
http://issues.umbraco.org/issue/U4-4049

**Comment by ProfessorFarnsworth** [comment]
As far as I understand the umbraco tickets its more a .net GDI+ problem. Hmm... But maybe my workaround lowers the chance of failed images a bit. We will see! ;)

**Comment by ProfessorFarnsworth** [comment]
Good morning sir :) I'm just tried to upload the images you provided via the vanilla umbraco uploader and it seems that thing has the same Problem as my uploader. So yeah. I don't think I can do much about it. Sad to say though. I'll take care about the black border thingy though :)

**Comment by ProfessorFarnsworth** [comment]
Ok the new version is online. Please try it out. I know that the GDI+ error is still there but as said. I can't do anything about it. :(
Best regards Helmuth

**Comment by bjarnef** [comment]
Yes, the Umbraco uploader also cause issues. With these images only "Lightair_Solution-1-.jpg" was created as a image node and the same with your uploader. However the issues with some images were created as file media items I haven't exspirienced in the core uploader. If there isn't already a issue open on issue tracker I think one should be created, because in Umbraco 7.2.1 the core file uploader for multiple files still is quite unstable and doesn't work well to editors.

http://www.lightair.dk/media/21485/lightair-evolution-led_july2014.jpg
http://www.lightair.dk/media/21488/lightair-signature-led_july2014.jpg
http://www.lightair.dk/media/21490/lightair-style-led_july2014.jpg
http://www.lightair.dk/media/21476/Lightair_Solution-1-.jpg

**Comment by bjarnef** [comment]
Maybe you can use these messages in log:

```
2015-02-08 12:59:51,334 [12] INFO  HTMLFileUplaod - 1 Files ready for upload.
2015-02-08 12:59:51,358 [12] INFO  HTMLFileUplaod - Uploading file 'Lightair_Solution-1-.jpg' - ContentLength:
2015-02-08 12:59:51,580 [12] INFO  HTMLFileUplaod - 1 Files ready for upload.
2015-02-08 12:59:51,596 [12] INFO  HTMLFileUplaod - Uploading file 'lightair-signature-led_july2014.jpg' - ContentLength:
2015-02-08 12:59:51,598 [12] INFO  HTMLFileUplaod - Received file 'lightair-signature-led_july2014.jpg' is an file
2015-02-08 12:59:51,598 [12] INFO  HTMLFileUplaod - 1 Files ready for upload.
2015-02-08 12:59:51,635 [12] INFO  HTMLFileUplaod - Uploading file 'lightair-evolution-led_july2014.jpg' - ContentLength:
2015-02-08 12:59:51,637 [12] INFO  HTMLFileUplaod - Received file 'lightair-evolution-led_july2014.jpg' is an file
2015-02-08 12:59:51,666 [12] INFO  HTMLFileUplaod - 1 Files ready for upload.
2015-02-08 12:59:51,678 [12] INFO  HTMLFileUplaod - Uploading file 'lightair-style-led_july2014.jpg' - ContentLength:
2015-02-08 12:59:51,680 [12] INFO  HTMLFileUplaod - Received file 'lightair-style-led_july2014.jpg' is an file
2015-02-08 12:59:51,845 [12] INFO  HTMLFileUplaod - Received file 'Lightair_Solution-1-.jpg' is an image
```

**Comment by ProfessorFarnsworth** [comment]
Ok I've commented on that ticket you where referring on before. Maybe the logs help them a little bit.

**Comment by bjarnef** [comment]
Great! Let's hope that will help them to fix the problem and improve the media upload :)

**Comment by ProfessorFarnsworth** [comment]
Hi bjarnef,

i've created a new case for this problem at Umbraco as the other one is referring to something similar.
So I would like to ask if you could share the Images with the Umbraco guys?
The NEW ticket would be: http://issues.umbraco.org/issue/U4-6246
