### ISSUE TITLE
Link/button to clear successfully uploaded files

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#16]
When uploading many files at the same time, it could be useful the clear all the rows, where files are successfully uploaded instead of removing one by one and then make it make clear which files are in progress. E.g. like this: http://www.infragistics.com/samples/aspnet/web-upload/multiple-upload

Another idea could be the sort successfully uploaded files together (maybe at the bottom).

**Comment by ProfessorFarnsworth** [comment]
Hi, regarding the sorting thing. What about automatically remove successfully uploaded items after for example 1 or 2 seconds?

**Comment by bjarnef** [comment]
Yes, it could be an idea. Not sure how it works with many files and if you notice the files that have been successfully uploaded?

**Comment by ProfessorFarnsworth** [comment]
That's true could be kind of tricky to check whether a file is uploaded or not. So lets stick with the Clear Button :)

**Comment by ProfessorFarnsworth** [comment]
Ok! The new version is available!
