### ISSUE TITLE
Upload icon overlap link text

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#17]
This seems to be an issue in v. 0.3.0 too :)

It should be enough to give add something like:
```
.dropzone .item { position: relative; }
```

![2015-02-10_19-57-42](https://cloud.githubusercontent.com/assets/2919859/6134182/b12a2652-b15f-11e4-9537-7399c9b8c5f7.jpg)

![2015-02-10_20-00-56](https://cloud.githubusercontent.com/assets/2919859/6134183/b35c5af8-b15f-11e4-8cf7-fd403a3dc4d0.jpg)

**Comment by ProfessorFarnsworth** [comment]
Weird, thought I tested that :(
I'll let you know when it's fixed :)

**Comment by ProfessorFarnsworth** [comment]
I think I finally corrected it :)
