### ISSUE TITLE
Clicking the button "Remove All Processed Items" look like rollback

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#18]
When you click the button "Remove All Processed Items" the progressbars starts to animate to 0% percent and look like they are rolling back?

Furthermore for each click it trigger the notification:
"Media saved: Media saved without any errors"

Maybe "just" remove the processed items or if it needs to display message, customize the message to a more specific message?

**Comment by ProfessorFarnsworth** [comment]
Hahaha :D would be fun to rollback the upload.

All of this is a bug! So I'll see when I could fix it ;)

**Comment by ProfessorFarnsworth** [comment]
Well the rollback seems to be something weird in the combination of angular and the bootstrap animation. I've removed the animation to prevent this behavior. But I still don't know why :(
Anyway, try it out!
