### ISSUE TITLE
Files in dashboard dropzone has underline as default

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#19]
Files in dashboard dropzone has underline as default because inheritance from: 
```.umb-dashboard-control a { text-decoration: underline; }```

![2015-02-10_20-23-03](https://cloud.githubusercontent.com/assets/2919859/6134642/0fc01336-b163-11e4-961e-7cdf5cb56c0f.jpg)

**Comment by ProfessorFarnsworth** [comment]
I know. Just was to lazy to change that. ;)
But you can contribute if you like to ;)

**Comment by ProfessorFarnsworth** [comment]
Should be fixed :)
