### ISSUE TITLE
Some images don't reach "successfully"

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#2]
Some images doesn't reach "successfully". It is probably a calculation issue since some of the first values are higher than the actual filesize.

![2015-02-05_00-09-32](https://cloud.githubusercontent.com/assets/2919859/6051810/ba3c45a6-accb-11e4-82ee-aa11fb9d0274.jpg)

**UPDATE**
These 3 files were not uploade because they were larger than 4MB (default allowed filesize). I am not sure if it is possible to display an red error bar because of they failed to upload?

**Comment by ProfessorFarnsworth** [comment]
Thanks for the feedback! I'll investigate this issue asap!
As far as I know it should be possible to display an error in this case.

**Comment by ProfessorFarnsworth** [comment]
Should also be fixed now.
