### ISSUE TITLE
Missing thumbnails after upload

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#21]
After upload it seems some thumbnails are missing. However if I follow the path there is a thumbnail and after some refresh/reload they become visible.

![2015-02-10_20-35-02](https://cloud.githubusercontent.com/assets/2919859/6134865/9849483e-b164-11e4-898e-1a2aeb7c970b.jpg)

It is like foreach refresh, one more thumbnail become visible.
![2015-02-10_20-39-12](https://cloud.githubusercontent.com/assets/2919859/6134942/1740d3dc-b165-11e4-85b6-874c2365fc22.jpg)

**Comment by ProfessorFarnsworth** [comment]
That's the GDI+ problem we already know. So I close this for now.
