### ISSUE TITLE
Dropzone cause overflow

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#3]
The dropdown has a width of 100% and because the editing area also have padding, it cause overflow and therefore horizontal scrollbar.

![2015-02-05_00-19-53](https://cloud.githubusercontent.com/assets/2919859/6051957/5a35c144-accd-11e4-9d7b-3ab3e504f10a.jpg)

It should be fixed by remove width: 100%; or set width: auto;

![2015-02-05_00-23-07](https://cloud.githubusercontent.com/assets/2919859/6051973/77434284-accd-11e4-852d-14875deb7023.jpg)

**Comment by ProfessorFarnsworth** [comment]
Should be fixed now.
