### ISSUE TITLE
Dragover should have some kind of feedback

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#4]
When you drag files over the dropzone, it should have some kind of feedback to the editor/user. Like the default file upload in Umbraco 7.

![2015-02-05_00-30-09](https://cloud.githubusercontent.com/assets/2919859/6052290/57470b92-acd1-11e4-8853-7c822898099b.jpg)

Some examples:
http://html5demos.com/dnd-upload
http://pba-web.bjarnefyrstenborg.dk/html5/HTML5_File_API/index.html
http://www.dropzonejs.com/
http://flowjs.github.io/ng-flow/
http://robertnyman.com/html5/fileapi-upload/fileapi-upload.html

**Comment by ProfessorFarnsworth** [comment]
Awesome idea! I'll try to implement that!

**Comment by ProfessorFarnsworth** [comment]
Should be implemented now :)
