### ISSUE TITLE
Tip: You can add the editor as a dashboard control

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#6]
You can add the upload editor as a dashboard control, so you also are able to upload files at root in Media section. Otherwise you have to create a folder to use it.

If you add this in /config/dashboard.config you will have to editor on the root when you click on "Media".
However the buttons "Select Files" and "Begin Upload" get an underline. So you could use !important in your CSS or maybe change from an <a> tag to a <button> tag.

However the upload don't seem to work here, so seem it need some changes to work there.

```
<section alias="HTML5MediaDashboardSection">
    <areas>
      <area>media</area>
    </areas>
    <tab caption="Upload">
      <control showOnce="false" addPanel="false" panelCaption="">
        /App_Plugins/FileUpload/views/editor.html
      </control>
    </tab>
  </section>
```

**Comment by ProfessorFarnsworth** [comment]
I already thought about that as well! That would be pretty cool idea. I'll see what I need to do to get that working after I've fixed all the bugs :)

**Comment by bjarnef** [comment]
I think you can find some inspiration in the core files. I think they have a view for the dashboard and other view for the folder.
Because there is a small difference between them: http://issues.umbraco.org/issue/U4-4093

**Comment by ProfessorFarnsworth** [comment]
I'm getting closer with the implementation. But there are still some tests todo :)

**Comment by ProfessorFarnsworth** [comment]
So this should finally work as well!
